name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_ios:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Add target
        run: rustup target add x86_64-apple-ios
      - name: Cache cargo install
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-install-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-dinghy
        run: |
          if ! command -v cargo-dinghy &> /dev/null
          then
            cargo install cargo-dinghy
          fi
      - name: Start iPhone simulator
        run: xcrun simctl boot "iPhone 14"
      - name: List simulators
        run: xcrun simctl list
      - name: Build and run tests
        run: cargo dinghy -d iphone test