name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_common_os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [stable]
        feature: [ no_feature , "eyre_support" ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Setup Feature Args
        shell: bash
        run: |
          if [[ "${{ matrix.feature }}" == "no_feature" ]]; then
            echo "FEATURE_ARGS=" >> $GITHUB_ENV
          else
            echo "FEATURE_ARGS=-F ${{ matrix.feature }}" >> $GITHUB_ENV
          fi
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ env.FEATURE_ARGS }}
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ env.FEATURE_ARGS }}
  build_test_android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [i686-linux-android, aarch64-linux-android, armv7-linux-androideabi, thumbv7neon-linux-androideabi, x86_64-linux-android]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --release --target ${{ matrix.target }}