name: Conventional Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: webiny/action-conventional-commits@v1.3.0